### ISSUE TITLE
Link to 'Full Readme' is broken.

### ISSUE THREAD

**Issue by TheLastMillennial** [MateoConLechuga/Oiram#10]
In the current readme.md, there's section that states there's a full readme at this link: https://github.com/mateoconlechuga/oiram/blob/master/packs/readme.md however, this link is broken and just takes you to a 404 error. I have not seen this page before but after looking through some folders, I think this may be what it's suppose to link to: https://github.com/mateoconlechuga/oiram/blob/master/extra/readme.md is this correct? If so, could the readme please be updated with the working link?

**Comment by mateoconlechuga** [comment]
should be fixed in e5c53a8
