### ISSUE TITLE
Getting past score of 9,999,990 causes overflow

### ISSUE THREAD

**Issue by TheLastMillennial** [MateoConLechuga/Oiram#11]
Some insane person actually got to the maximum score possible [here](https://youtu.be/8uYPtqPA848?t=46). Once they reached the maximum score allowed in SM3, it caused a classic overflow. To the best of my knowedge, the original game only lets you reach 9,999,990 and doesn't overflow.

I attempted to fix this myself by adding a simple check after line 75 and 84 [in lower.c](https://github.com/mateoconlechuga/oiram/blob/master/src/lower.c) that would set the score back to 9,999,990 if the new score was bigger than that.

`if(game.score > 9999990) {
    game.score = 9999990;
 }`

Although this fixed the overflow bug, it broke the traveling through pipes animation so Oiram suddenly started teleporting between pipes rather than going through them. I don't understand how messing with the score broke the pipes, could this please be explained?

**Comment by mateoconlechuga** [comment]
I like this bug though :)

**Comment by TheLastMillennial** [comment]
Yeah it is sort of a neat 'Easter egg' for reaching such a score. I suppose it makes sense to keep it.
