### ISSUE TITLE
Bug with invincible mode

### ISSUE THREAD

**Issue by RomainL972** [MateoConLechuga/Oiram#12]
If Mario is in invincible mode when he enters the pipe at the end of level 10, he stays invincible and slays all monsters by touching them including thwomps and fireballs. He stays that way until he dies, by fire for example.

**Comment by marauder316** [comment]
This actually happens with *all* levels in all packs, not just Level 10 in
the Default Pack.
The effect resets if you collect another Super Star or die.

**Comment by mateoconlechuga** [comment]
This is a feature actually! There are level packs that depend on this.
