### ISSUE TITLE
How to fly in Oiram

### ISSUE THREAD

**Issue by lafkpages** [MateoConLechuga/Oiram#13]
Hi,

I've played Mario before but I've never known what the squirrel was for. A friend told me you could fly with it, but we don't know how to. I've tried pressing the up arrow and 2nd simultaneously, but I still can't fly.
Does someone know how to?

**Comment by mateoconlechuga** [comment]
You have to run and gain enough speed until the white bar in the bottom is full, and then you can repeatedly press the jump button.

**Comment by lafkpages** [comment]
Thanks! It works.
