### ISSUE TITLE
When you finish a level you start at the end

### ISSUE THREAD

**Issue by lafkpages** [MateoConLechuga/Oiram#14]
I'm not sure if it's supposed to be like this, but when you finish a level pack and you play it again later, you start at the last level, so if I wan't to play the entire pack again, I have to constantly die if I can, and otherwise wait 10 minutes per life. And sometimes I get to 99 lives...

**Comment by mateoconlechuga** [comment]
You can use the left and right arrow keys at the level selection screen to choose what level you want to play.

**Comment by mateoconlechuga** [comment]
As a side note, it literally says this on the title screen "Press <> to select level".
