### ISSUE TITLE
Oiram won't start and just says “libs”

### ISSUE THREAD

**Issue by lafkpages** [MateoConLechuga/Oiram#15]
When I go to apps, and select Cesium and run OIRAM, all I see is a text that says `libs`. It also got renamed and it was OIRAM and some other weird characters after.

![image](https://user-images.githubusercontent.com/62298468/130462770-45804f18-f0df-4657-908d-87cab6a57476.png)

And I have all these libraries:
- `FILEIOC`
- `FONTLIBC`
- `KEYPADC`

Am I missing any?

**Comment by mateoconlechuga** [comment]
The graphx library? It should come with the clibs download. I'm not sure what caused this particular issue... You aren't building Oiram correct?

**Comment by mateoconlechuga** [comment]
It sounds like some other program may have corrupted your symbol table. You might try a reinstall by wiping all of memory in the reset menu.

**Comment by lafkpages** [comment]
I have `GRAPHX`, just didn't see it in TI Connect \\:

**Comment by lafkpages** [comment]
I also have `IGRAPH` and `LibLoad`... (sorry)

**Comment by ChrisvanChip** [comment]
Does it work if you use it using the CabriJr app instead of Cesium? (To get an idea where the issue is located)
