### ISSUE TITLE
Oiram unable to move

### ISSUE THREAD

**Issue by JewishBanana** [MateoConLechuga/Oiram#2]
Hi I was wondering if anybody could help me. Basically I downloaded ce c libraries and i downloaded Oiram I did everything right and when I enter the game, my character cannot move at all and I can't even exit the game I have to reset my ram. But everything else moves the blocks move the enemies move and they even kill me (and when I run out of lives and go to the title screen I can exit the program) so I do not understand whats happening please anybody tell me.

**Comment by adriweb** [comment]
So, it turns out we're dealing with this exact issue as of "recently" with someone else in particular (and others)...

It appears there is some issues with recent hardware revisions of the CE calculators, ie. they don't work the same way as the previous revisions... which breaks things (for instance, pressing keypad buttons doesn't work anymore).
For now there's no solution, you'll have to press the reset button on the back and monitor updates of Oiram, libraries, and such :/

Just to make sure, can you tell us what calculator you have exactly and its hardware revision: it's something like `L-0816E` on the back , to the right of the serial number.

**Comment by JewishBanana** [comment]
I have a TI-84 Plus CE and I had the exact same calculator a few days ago but I exchanged it for reasons but it worked 100% fine on that calculator I even made my own level pack. The hardware revision is L-03171

**Comment by adriweb** [comment]
Okay thanks, that's actually `L-0317I` which is precisely a version known to have the issue.
Make sure to subscribe to https://github.com/CE-Programming/toolchain/issues/86  to know when a fix is available.

The other calculator you swapped was probably "the same" but an older hardware revision, which has internal changes.

**Comment by mateoconlechuga** [comment]
You should email TI and ask what they changed in their hardware revision :)

**Comment by ninjapepes** [comment]
I have L-0517 and can not move either. I just got this calculator a few days ago.

**Comment by mateoconlechuga** [comment]
@ninjapepes If you wouldn't mind; I do have some tests to help resolve this issue as quickly as possible if you wouldn't mind testing them? It would be a big help. The same for @davidclue

**Comment by ninjapepes** [comment]
I'm down.

**Comment by mateoconlechuga** [comment]
@ninjapepes @davidclue would you mind running this on your calculator and telling me what the output is?

https://usercontent.irccloud-cdn.com/file/CxICEL8d/DEM.8xp

It should be runnable as `Asm(prgmDEM`

**Comment by mateoconlechuga** [comment]
@ninjapepes @davidclue Also this program as well; you should be able to press the [on] key and it will exit:

https://usercontent.irccloud-cdn.com/file/NwiRvX5k/DEM2.8xp

Note that this one is still runnable via `Asm(prgmDEM`, it may freeze so you will have to press the reset button on the back if that happens. Thanks for the help!

**Comment by ninjapepes** [comment]
Before I do this is there any way to backup my data so I don't have to reinstall all the games I already have on here?

**Comment by mateoconlechuga** [comment]
You can place everything in the archive by pressing [2nd][+][2][1], and pressing the [enter] key to add an asterisk next to the variables you don't want to be deleted accidentally. These programs shouldn't do anything that would do that though; but I do like playing it safe :)

**Comment by ninjapepes** [comment]
I just tried the first one and it said Good... Done.

**Comment by mateoconlechuga** [comment]
Awesome work! The second one should quit now by pressing [on].

**Comment by ninjapepes** [comment]
Oh. I tried the second one but it froze. I didn't try on though.

**Comment by mateoconlechuga** [comment]
Yep; it should look like it froze but pressing [on] should in theory quit the program. If you wouldn't mind just making sure; that would be great :)

**Comment by ninjapepes** [comment]
I just tried it again and nothing is happening when I press on. I wanted to take a screenshot to show you, but TI Connect CE says that it's not connected. I guess that means it's frozen/not working?

**Comment by mateoconlechuga** [comment]
Yep; so now we know where to look for the error. Thanks again; shouldn't be too bad to fix now :)

**Comment by JewishBanana** [comment]
I just finished the tests the first one when I run it, it says "good" and when I run the second one it freezes the calculator

**Comment by mateoconlechuga** [comment]
Thanks @davidclue!

For information; it looks to be an issue with the interrupt controller or with interrupt generation itself.

**Comment by davidclue** [comment]
By any chance do you have a guide or anything that can help teach me any programming of TI-84 CE programming specifically. I really want to program my own games on TI-84 CE but I don't know how to learn, so if you have anything that can help me please reply.

**Comment by mateoconlechuga** [comment]
https://www.cemetech.net is a great place to start learning and asking questions; you can also visit http://tibasicdev.wikidot.com for information on learning the TI-BASIC language which is a nice starter language. :)

**Comment by davidclue** [comment]
https://www.manning.com/books/programming-the-ti-83-plus-ti-84-plus

Will this teach me TI-84 Plus CE programming cause it says it will on cemetech but just read the title.

**Comment by KermMartian** [comment]
This will teach you TI-83 Plus/TI-84 Plus programming commands that work on the monochrome and color calculators. It was written before the color calculators came out, so there's an Appendix that tells you the few commands that are different on the color calculators (mostly things like the different homescreen and graphscreen commands, and how to use text and drawing colors): download the free Appendix D after you purchase the book: https://www.manning.com/books/programming-the-ti-83-plus-ti-84-plus . Also, please feel free to post your programming questions (and questions about the book) on Cemetech!

**Comment by mateoconlechuga** [comment]
Here's another three tests to try out if you get a chance @davidclue @ninjapepes. Be sure to turn your calculator `off` and then `on` before launching.

https://usercontent.irccloud-cdn.com/file/rtaoBWYj/DEM3.8xp

Please just let me know exactly what numbers and/or other things it prints out for this one.

https://usercontent.irccloud-cdn.com/file/KYkLhzrl/DEM4.8xp

This test should operate just like the first `DEM`. So just whatever it prints put it here.

https://usercontent.irccloud-cdn.com/file/RmTwc0Zx/DEM5.8xp

This test will either not print anything or print a number. If it prints anything, that would be good to know.

Thanks again for the help!

---

For the curious here is the test codes:

DEM3: http://www.rafb.me/results/UoNhK567.html
DEM4: http://www.rafb.me/results/s1VHij11.html
DEM5: http://www.rafb.me/results/EK6xMe20.html

**Comment by JewishBanana** [comment]
DEM3: The calculator freezes.

DEM4: Output is "good".

DEM5: Just instantly closes with no message.

**Comment by davidclue** [comment]
If it's possible can you please help me with my code I don't get where I'm going wrong I'm a beginner and I created a simple test program but I want that when I press clear the program closes and clrhome's
but it doesn't work, here is the script. And also can you tell me what code editor you used to make Oiram?


Repeat K=45
getKey→K
Disp "A >/< B?"
Prompt A,B
If A>B
Disp "A is greater then B"
If A<B
Disp "B is greater then A"
Disp "=========================="
End
ClrHome
Return

**Comment by KermMartian** [comment]
This is a question that would be much more appropriate for [the TI-BASIC subforum on Cemetech](https://www.cemetech.net/forum/viewforum.php?f=19) or elsewhere. Oiram is not written in TI-BASIC; for TI-BASIC, other than programming directly on the calculator, there are various options like the TI-BASIC editor in TI Connect CE and [SourceCoder 3](http://sc.cemetech.net).

**Comment by mateoconlechuga** [comment]
@davidclue @ninjapepes Alright; these tests should do one of 2 things: crash or freeze the calculator. Please be sure to backup; and just let me know which is does. Thanks!

https://usercontent.irccloud-cdn.com/file/tl01fHKZ/DEM.8xp
https://usercontent.irccloud-cdn.com/file/z260uSFF/DEM2.8xp

Run with `Asm(prgmDEM`

---

Source files; just ignore.

DEM: http://www.rafb.me/results/vpcjCY73.html
DEM2: http://www.rafb.me/results/MgrEzx88.html

---

Initial findings:

Nothing appears to be wrong with the regions of memory used to lock the interrupt vector addresses or the jump location stored in the sha256 chip. Rather, it appears as if mode 2 interrupts don't work properly. These tests will prove this.

**Comment by JewishBanana** [comment]
The first one DEM.8xp it just said Done and crashed my calculator with a second delay to do so.

The second one DEM2.8xp moved the cursor of the home screen near the bottom and instantly crashed the calculator without saying done.

**Comment by mateoconlechuga** [comment]
Do you mean that you had enough time to see where the cursor went before the crash occured? You may want to make sure you didn't have the usb plugged in when testing; just to be sure :)

**Comment by adriweb** [comment]
Even with USB plugged in, though, on a rev. E, both programs cause an instant crash - absolutely no delay at all.

**Comment by JewishBanana** [comment]
No there was a delay and I saw the cursor appear near the bottom and then it froze there, it was a one second delay because the cursor flicked before it crashed.

**Comment by adriweb** [comment]
Right, so it's definitely different and we don't really know what's going on :P

**Comment by LarrytheMoos** [comment]
when do y

**Comment by LarrytheMoos** [comment]
when do you think it can be upgraded* (accidentally hit comment)

**Comment by mateoconlechuga** [comment]
When I get another calculator today; I'll be able to tell you more. I wish I could tell you exactly when; but it is still too soon to tell.

**Comment by LarrytheMoos** [comment]
ok

**Comment by mateoconlechuga** [comment]
TI has broken support for interrupt handling on the TI84+CE past revision I. What this means is that Oiram will need to be modified to not use interrupts. I am unsure of how long this process will take; but I will do my best.

**Comment by mateoconlechuga** [comment]
Oiram should now work correctly across everyone's calculator. Enjoy! You can find the download link here:

https://www.cemetech.net/programs/index.php?mode=file&id=1526

Be sure to resend all of the files and read the readme. Thanks again for everyone's help!

Closing this issue as it has now been resolved.

**Comment by davidclue** [comment]
I think you can jump a block higher and you go a bit slower than you used to. The fire balls are shooting 2 at once every time and theirs a longer delay to shoot, and I can't get the raccoon Oiram to work (flying). Theirs also a delay with when you stop moving you continue to walk a few steps, also I don't know if before this happened but when you step on red platforms they fall one block and vanish (I think it used to be three). You can't pick up shells when you go near them and tap [alpha] or hold [alpha], last but not least the instructions in the readme file are completely different then the ones in game. These are just some bugs to fix if you decide to.

**Comment by mateoconlechuga** [comment]
The controls are configurable; have you read the splash screen which even lists the controls for you; and how the control mode can be changed via the [mode] button? It works exactly as the original game; and yes you move after you stop holding down; it does that in the original. The red platforms vanish. The jump height is 4 blocks high; the screen is just shorter so it seems off. Remember, to use Racoon Oiram you need to sprint and then use the jump button. That's what the white meter bar is for.

For future reference; it is spelled `There's` and not `Theirs`.

As for the fireballs and picking up shells; yes that is broken. It is a side effect to make it work with your calculator. I'll try and fix that as soon as I can. Just press the key quickly and it works fine.

**Comment by mateoconlechuga** [comment]
You can get the fireball and shell pickup fixes here:

https://tiplanet.org/forum/archives_voir.php?id=123456

Thanks for the reports; it's just upsetting to keep having to fix things.
