### ISSUE TITLE
my ethernet ipv4 is 192.168.3.178

### ISSUE THREAD

**Issue by eschan145** [MateoConLechuga/Oiram#20]

**Comment by lafkpages** [comment]
The thing that you can go through blocks is intended I think, because in many levels you need to do it to win

**Comment by mateoconlechuga** [comment]
> but an not sure on how to get to them

They are easter eggs for that very reason. And no, I will not be adding more enemies.

**Comment by lafkpages** [comment]
> no, I will not be adding more enemies

Yeah, seems like a lot of work to make a game for a calculator.

**Comment by CommentedNewline** [comment]
Maybe I found every easter egg in oiram. Just Maybe.
