### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by sigmasan** [MateoConLechuga/Oiram#8]
I'm trying to compile a custom build of Oiram, but it doesn't seem to be working. Whenever I try
`make -C img`
it pulls up this:
`make: Entering directory C:/Users/natha/Downloads/oiram-master/img'
convpng
process_begin: CreateProcess(NULL, convpng, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [cv] Error 2
make: Leaving directory C:/Users/natha/Downloads/oiram-master/img'`
My father and I have tried adding main_pal.png and convimg, but nothing works, even though I'm using fasmg. What am I doing wrong?

**Comment by mateoconlechuga** [comment]
I am in the process of moving Oiram to the new (unreleased) llvm based toolchain. However, you should be able to build Oiram with commit 8c28e6e and toolchain version 8.7. I apologize for this, but there are a lot of difference and toolchain changes that are being made currently, so I can't really say yet when everything will work again.

**Comment by sigmasan** [comment]
So, I should use toolchain 8.7 instead of 8.8?

**Comment by mateoconlechuga** [comment]
That is correct. Note that you should use the latest toolchain if you plan to make your own programs, but for now this is a quick solution.

**Comment by sigmasan** [comment]
OK. I followed your instructions, and it worked better, but it's still returning an error:
`mkdir ../bin
The syntax of the command is incorrect.
make: *** [cv] Error 1
make: Leaving directory C:/Users/natha/Downloads/oiram-master/img''`
Is there still something I'm forgetting?

**Comment by mateoconlechuga** [comment]
No I just haven't tested on windows in forever, that's my fault again. Create a folder called "bin" in the topmost directory first, and just remove the "$(MKDIR) ../bin" line completely from the makefile file in the img folder, and try again.

**Comment by sigmasan** [comment]
It's now returning this:
`export INCLUDE="C:\CEdev/include/fasmg-ez80" && fasmg oiram_tiles.ez80 OiramT.8xv
'export' is not recognized as an internal or external command,
operable program or batch file.
make: *** [sp] Error 1
make: Leaving directory C:/Users/natha/Downloads/oiram-master/img'`
Perhaps something is still wrong?

**Comment by adriweb** [comment]
Hmm isn't it "set" instead of "export" or windows? Anyway, looks like you're getting closer lol

**Comment by sigmasan** [comment]
"Set" seemed to work better. Now I'm getting this:
`set INCLUDE="C:\CEdev/include/fasmg-ez80" && fasmg oiram_tiles.ez80 OiramT.8xv
flat assembler  version g.ice6x-ez80
oiram_tiles.ez80 [1]:
        include 'ez80.inc'
Processed: include 'ez80.inc'
Error: source file not found.
make: *** [sp] Error 2
make: Leaving directory C:/Users/natha/Downloads/oiram-master/img'`
I checked fasmg-ez80 and saw ez80.inc there. Is it supposed to be in img instead?

**Comment by adriweb** [comment]
I'm not sure if it should, but does it make it go further if you do indeed copy the file there?
Might be a temporary fix just for this `make` step but something looks odd with the paths set up though (well, at least it did find fasmg, so...)

**Comment by sigmasan** [comment]
It got further, and after adding tiformat.inc, which also made it go further, I see this:
`set INCLUDE="C:\CEdev/include/fasmg-ez80" && fasmg oiram_tiles.ez80 OiramT.8xv
flat assembler  version g.ice6x-ez80
oiram_tiles.ez80 [3]:
        format ti archived appvar 'OiramT'
macro ti [75] macro dw [2]:
        emit word?: @values
Processed: emit word?: sizeof all
Error: value out of allowed range.
make: *** [sp] Error 2
make: Leaving directory C:/Users/natha/Downloads/oiram-master/img'`
Is there a token I need to change?

**Comment by DT-is-not-available** [comment]
has this been solved? I'm having the same problem now

**Comment by DT-is-not-available** [comment]
Welp, all you have to do is copy everything in the C:\CEdev\include\fasmg-ez80 folder into img and it does it perfectly, ending with an error that fails to move it to the bin folder. But the variables work just fine now, and custom images are showing up in-game!
![image](https://user-images.githubusercontent.com/66632141/84302965-2f5cba80-ab24-11ea-84af-49fc537304fb.png)

**Comment by mateoconlechuga** [comment]
Oiram should now build without issues using the latest CE C Toolchain release: https://github.com/CE-Programming/toolchain/releases/latest
