### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by M4xi1m3** [MateoConLechuga/Oiram#9]
Oiram is distributed without a license, thus putting it under strict copyright by default. Would you mind adding a license to the project?

**Comment by mateoconlechuga** [comment]
What license do you want?

**Comment by M4xi1m3** [comment]
I don't know, up to you to see if you want a strict copyleft license (GNU GPL) or a less strict license (MIT/BSD). I was thinking of porting oiram to another platform, that's why I'm asking.

**Comment by mateoconlechuga** [comment]
Added: https://github.com/mateoconlechuga/oiram/commit/001a2ac556d98feec76d323239ae638cf8b43ec4
